apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: denyenv-selfsigned-issuer
  namespace: default
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: denyenv-tls-secret
spec:
  duration: 8760h
  renewBefore: 8000h
  subject:
    organizations:
      - zeng.dev
  commonName: denyenv.default
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - digital signature
    - key encipherment
    - server auth
  dnsNames:
    - denyenv
    - denyenv.default
    - denyenv.default.svc
  ipAddresses:
    - 192.168.1.10 # change it to your IP addresses
  issuerRef:
    kind: Issuer
    name: denyenv-selfsigned-issuer
  secretName: denyenv-tls-secret